#!/bin/sh

set -o errexit

echoerr() 
{ 
    echo "$@" 1>&2 
}

repl() 
{
     printf "$1"'%.s' $(eval "echo {1.."$(($2))"}")
} 

clearLine() 
{
    printf "\r"
    repl " " $1
    printf "\r"
}

clearPrintLast=""

clearPrint()
{
    clearLine ${#clearPrintLast}
    clearPrintLast="$@"
    printf "$@"
}

size=$1
count=$2
checksum=$3

if test -z $1; then
    echoerr "Missing size argument"
    exit 1
fi

if test -z $2; then
    count=1
elif test $2 -lt 1; then
    echoerr "Count argument must be more than 1"
    exit 1
fi

if test -z $3; then
    checksum=sha1sum
fi

basename=random-$1-

size=$(numfmt --from=iec $1)
checksumFile="checksums-${checksum}.txt"

printf "" > ${checksumFile}

for (( i=1; i <= count; i++ )); do
    file=${basename}${i}.bin

    clearPrint "Generating ${file}"

    head -c ${size} /dev/urandom > ${file}
    
    clearPrint "Checking ${file}"
    
    fileSize=$(stat --printf="%s" ${file})

    if test $fileSize -ne $size; then
        echoerr "File size miss match. Target: ${size} Actual: ${fileSize}"
        exit 1
    fi

    $checksum ${file} >> ${checksumFile}

    clearPrint "Done ${file}\n"

done

echo "Verifying files"

$checksum -c ${checksumFile}
